set -g status-right "\
#[bg=white,fg=blue] #{host_short} \
#[bg=red,fg=white] #(whoami) \
#[bg=white,fg=red] #{session_name} \
#[bg=red,fg=white] \
#[bg=white,fg=red] $SHELL  \
#[default]"
set -g mouse on
