set -g status-style fg=white,bg=blue
set -g window-status-current-format "#[bg=white,fg=blue]#[bg=blue,fg=white]#I:#W#[bg=white,fg=blue]"
set -g window-status-format "#[bg=blue,fg=white]   #I:#W "
set -g status-right "\
#[bg=white,fg=blue] #{host_short} \
#[bg=red,fg=white] #(whoami) \
#[bg=white,fg=red] #{session_name} \
#[bg=red,fg=white] \
#[bg=white,fg=red] $SHELL  \
#[default]"
set -g mouse on

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin "arcticicestudio/nord-tmux"

run '~/.tmux/plugins/tpm/tpm'