alias val='ruby /home/daisuke/src/sleep/validate.rb '
alias val2='ruby /home/daisuke/src/sleep/validate_2.rb '
alias sls='ruby /home/daisuke/src/sleep/translate_sleep_time_2.rb '
alias slm='ruby /home/daisuke/src/sleep/translate_meal_time.rb '
alias slk='ruby /home/daisuke/src/sleep/abstract_kibun.rb '

alias vag='vagrant'
alias rs='rsync'
alias wh='which'
alias re='ruby -e'
