format = """
[](bg:blue fg:white)\
$username\
[ $directory ](bg:color_1 fg:color_2)\
$git_branch\
$git_status\
$time\
[ ](bg:none fg:color_1)
> 
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
palette = 'ieremii'

[palettes.ieremii]
color_0 = 'blue'
color_1 = 'white'
color_2 = 'yellow'
color_3 = 'black'

[username]
show_always = true
style_user = "bg:color_0 fg:color_1"
style_root = "bg:#9A348E"
format = '[ $user ]($style)'
disabled = false

[directory]
format = "[$path](none)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:color_2 fg:color_1"
format = '[  $symbol $branch  ]($style)'

[git_status]
style = "bg:color_1 fg:color_2"
format = '[ $all_status$ahead_behind ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:color_2 fg:color_1"
format = '[ $time ]($style)'
