# Default colors
[colors.primary]
background = '#3f3f3f'
foreground = '#e6edf9'

# Normal colors
[colors.normal]
black   = '#080d10'
white   = '#e6edf9'
blue    = '#00205b'
cyan    = '#0D47A1'
red     = '#1565C0'
green   = '#1976D2'
yellow  = '#1E88E5'
magenta = '#2196F3'

# Bright colors
[colors.bright]
black   = '#23272c'
white   = '#f5f5f5'
blue    = '#0b8bee'
cyan    = '#42A5F5'
red     = '#64B5F6'
green   = '#90CAF9'
yellow  = '#BBDEFB'
magenta = '#E3F2FD'
